### ISSUE TITLE
no hostname/nodename information logged

### ISSUE THREAD

**Issue by databus23** [vmware/kube-fluentd-operator#16]
I noticed that the events do not contain any hints from which node they were shipped. This makes it very hard to reason about systemd logs (e.g. which kubelet emitted this error?).
I think it would be generally good to have the node name attached to every log line emitted. This should be doable using the downardAPI and just handing the nodename via env/flag to the config generator.

**Comment by databus23** [comment]
So this sort of works:
```
      - command:
        - /bin/config-reloader
       ...
        - --meta-key=metadata
        - --meta-values=node=$(NODE_NAME)
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
```
