### ISSUE TITLE
Publish a spec for fluentdconfigs crd, so it can be installed separately

### ISSUE THREAD

**Issue by alex-vmw** [vmware/kube-fluentd-operator#188]
Publish a spec for fluentdconfigs crd, so it can be installed separately. We do not install kube-fluentd-operator via a helm chart, but install it manually via a yaml manifest, so I am not sure if Helm is designed to wait for the CRD to be created first before it tries to create any CRDs of type fluentdconfigs. If the kube-fluentd-operator itself installs the fluentdconfigs crd it takes some time for it to get created, which means we can't create admin ns configuration together with the kube-fluentd-operator. It would be much nicer if you just publish fluentdconfigs crd separately, so it can be pre-installed prior to creating the admin ns configuration.

**Comment by alex-vmw** [comment]
In case anyone find this issue and is interested the CRD is currently as follows:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fluentdconfigs.logs.vdp.vmware.com
  spec:
    conversion:
      strategy: None
    group: logs.vdp.vmware.com
    names:
      kind: FluentdConfig
      listKind: FluentdConfigList
      plural: fluentdconfigs
      singular: fluentdconfig
    scope: Namespaced
    versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                fluentconf:
                  type: string
              type: object
          type: object
      served: true
      storage: true
```
