### ISSUE TITLE
Volume mount is not working as expected

### ISSUE THREAD

**Issue by armensuri** [vmware/kube-fluentd-operator#213]
I'm trying to mount a volume to pull secret into a file. Following the instructions I added this code to my values.yaml
```
extraVolumes:
  - name: my-secret
    secret:
      defaultMode: 420
      secretName: mysecret-service

log-router:
....
....
  fluentd:
    extraEnv: {}
    resources:
      limits:
        cpu: 600m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 200Mi
    extraVolumeMounts:
      - name: my-secret
        mountPath: /fluentd/certs
        readOnly: true
```

I get the following error when building : 
```
cannot patch "logging" with kind DaemonSet: DaemonSet.apps "logging" is invalid: spec.template.spec.containers[0].volumeMounts[4].name: Not found: "my-secret"
                                upgrade.go:367: [debug] warning: Upgrade "g7c7c7fc-2a70-46f4-a50a-dfb50184def2" failed: cannot patch "logging" with kind DaemonSet: DaemonSet.apps "logging" is invalid: spec.template.spec.containers[0].volumeMounts[4].name: Not found: "my-secret"
```

I was able to directly modify the daemonset using Lens and was able to get it working. I'm suspecting that there is an issue with the block that I defined in values.yaml getting properly substituted in daemonset.yaml might be some yaml formatting issue. is there anything in the yaml I defined in values.yaml that jumps out?

Thanks,
Armen
