### ISSUE TITLE
Failed to expand log record

### ISSUE THREAD

**Issue by MartinAltmayer** [vmware/kube-fluentd-operator#23]
While fluentd-operator works great for most of my pods, the logs of some pods are lost. Instead I receive the following error messages in the fluentd logs. So far I did not find a pattern which pods are affected.

```
2018-08-07 08:41:30 +0000 [warn]: #0 dump an error event: error_class=RuntimeError error="failed to expand `record[\"kubernetes\"][\"labels\"][\"parselogs\"]&.gsub(/[.-]/, '_') || '_'` : error = undefined method `[]' for nil:NilClass" location="/var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/filter_record_transformer.rb:310:in `rescue in expand'" tag="kube.site-delta.oneshot-5c7hc.test" time=2018-08-07 08:40:50.846153013 +0000 record={"log"=>"Ciao Delta!\n", "stream"=>"stdout", "docker"=>{"container_id"=>"5229dd14d74e921a72c7f294c1b2766d6e8b57f68cedaf46b192c2be7d44ac2b"}, "kubernetes"=>{"container_name"=>"test", "namespace_name"=>"site-delta", "pod_name"=>"oneshot-5c7hc", "pod_id"=>"5229dd14d74e921a72c7f294c1b2766d6e8b57f68cedaf46b192c2be7d44ac2b", "namespace_labels"=>{"name"=>"site-delta"}}, "container_info"=>"5229dd14d74e921a72c7f294c1b2766d6e8b57f68cedaf46b192c2be7d44ac2b-stdout"}
```

In fact, the "kubernetes" section does not contain any labels, although the pod is labelled.

The namespaces' fluentd-config is as simple as

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |-
    <filter $labels(parselogs=python)>
      @type parser
      key_name log
      format /^(?<time>[^\[]*) \[(?<level>[^\]]*)\] (?<logger>[^:]*):(?<message>.*)$/
    </filter>

    <match **>
      @type loggly
      loggly_url <my-loggly-url>
    </match>
```

With the following simple job I am sometimes able to reproduce the issue:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
  labels:
    component: logging-test
spec:
  parallelism: 5  # Not necessary
  completions: 5  # but might help to reproduce the issue
  template:
    metadata:
      labels:
        component: logging-test
    spec:
      restartPolicy: Never
      containers:
      - name: test
        image: <some_image>
        imagePullPolicy: Always
        command: ['bash']
        args:
          - '-c'
          - |
            set -eu
            echo "Hallo Delta!"
            sleep 10s
            echo "Ciao Delta!"
```

I use version 1.6.0 from log-router-0.2.3.tgz.
