### ISSUE TITLE
Update kubectl/manifests.yaml file with latest ClusterRole permissions

### ISSUE THREAD

**Issue by alex-vmw** [vmware/kube-fluentd-operator#261]
Update kubectl/manifests.yaml file with latest ClusterRole permissions.
Looks like the below required permission is missing:
```
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - update
```
